#!/bin/sh
# Add this file into your path for run quicker :>
# > PATH=$PATH:$(pwd)

ui_file_path=./resources/components/ControlCenter.ui
uipy_file_path=./resources/components/Ui_ControlCenter.py
py_file_path=./ControlCenter.py

python_version=$(python --version | grep "Python 3.8")
echo "Interpreter: $python_version"
echo
# clear

# check python_version is empty? Empty <-> Not found python 3.8
if [ -z "$python_version" ]; then
    echo "Python 3.8.x is required!"
    echo "Aborting!"
    exit 1
fi

if [ -f $ui_file_path ]; then
    echo "Found \e[93m$ui_file_path\e[0m!"
    echo "Convert: $ui_file_path ---> $uipy_file_path"
    pyuic6 $ui_file_path -o $uipy_file_path
    echo "Done!"
    echo
else
    echo "Not found \e[93m$ui_file_path\e[0m!"
    echo "Aborting..."
    exit 1
    echo
fi

if [ -f $py_file_path ]; then
    echo "Found \e[93m$py_file_path!\e[0m"
    echo "Start $py_file_path"
    python $py_file_path
    echo "Done!"
    echo

else
    echo "Not found $py_file_path!"
    echo "Aborting..."
    exit 1
    echo

fi