# Form implementation generated from reading ui file './resources/components/ControlCenter.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 713)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MonitorGroup = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.MonitorGroup.setGeometry(QtCore.QRect(10, 10, 551, 411))
        self.MonitorGroup.setObjectName("MonitorGroup")
        self.PresetMode_1 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.PresetMode_1.setGeometry(QtCore.QRect(570, 10, 151, 131))
        self.PresetMode_1.setObjectName("PresetMode_1")
        self.Run_1 = QtWidgets.QPushButton(parent=self.PresetMode_1)
        self.Run_1.setGeometry(QtCore.QRect(20, 30, 111, 26))
        self.Run_1.setObjectName("Run_1")
        self.Load_1 = QtWidgets.QPushButton(parent=self.PresetMode_1)
        self.Load_1.setGeometry(QtCore.QRect(20, 60, 111, 26))
        self.Load_1.setObjectName("Load_1")
        self.Clear_1 = QtWidgets.QPushButton(parent=self.PresetMode_1)
        self.Clear_1.setGeometry(QtCore.QRect(20, 90, 111, 26))
        self.Clear_1.setObjectName("Clear_1")
        self.PresetMode_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.PresetMode_2.setGeometry(QtCore.QRect(570, 150, 151, 131))
        self.PresetMode_2.setObjectName("PresetMode_2")
        self.Run_2 = QtWidgets.QPushButton(parent=self.PresetMode_2)
        self.Run_2.setGeometry(QtCore.QRect(20, 30, 111, 26))
        self.Run_2.setObjectName("Run_2")
        self.Load_2 = QtWidgets.QPushButton(parent=self.PresetMode_2)
        self.Load_2.setGeometry(QtCore.QRect(20, 60, 111, 26))
        self.Load_2.setObjectName("Load_2")
        self.Clear_2 = QtWidgets.QPushButton(parent=self.PresetMode_2)
        self.Clear_2.setGeometry(QtCore.QRect(20, 90, 111, 26))
        self.Clear_2.setObjectName("Clear_2")
        self.PresetMode_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.PresetMode_3.setGeometry(QtCore.QRect(570, 290, 151, 131))
        self.PresetMode_3.setObjectName("PresetMode_3")
        self.Run_3 = QtWidgets.QPushButton(parent=self.PresetMode_3)
        self.Run_3.setGeometry(QtCore.QRect(20, 30, 111, 26))
        self.Run_3.setObjectName("Run_3")
        self.Load_3 = QtWidgets.QPushButton(parent=self.PresetMode_3)
        self.Load_3.setGeometry(QtCore.QRect(20, 60, 111, 26))
        self.Load_3.setObjectName("Load_3")
        self.Clear_3 = QtWidgets.QPushButton(parent=self.PresetMode_3)
        self.Clear_3.setGeometry(QtCore.QRect(20, 90, 111, 26))
        self.Clear_3.setObjectName("Clear_3")
        self.Device_Control_1 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.Device_Control_1.setGeometry(QtCore.QRect(730, 10, 281, 411))
        self.Device_Control_1.setObjectName("Device_Control_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Control Center"))
        self.MonitorGroup.setTitle(_translate("MainWindow", "System Monitor"))
        self.PresetMode_1.setTitle(_translate("MainWindow", "Preset - Mode 01"))
        self.Run_1.setText(_translate("MainWindow", "Run"))
        self.Load_1.setText(_translate("MainWindow", "Load"))
        self.Clear_1.setText(_translate("MainWindow", "Clear"))
        self.PresetMode_2.setTitle(_translate("MainWindow", "Preset - Mode 02"))
        self.Run_2.setText(_translate("MainWindow", "Run"))
        self.Load_2.setText(_translate("MainWindow", "Load"))
        self.Clear_2.setText(_translate("MainWindow", "Clear"))
        self.PresetMode_3.setTitle(_translate("MainWindow", "Preset - Mode 03"))
        self.Run_3.setText(_translate("MainWindow", "Run"))
        self.Load_3.setText(_translate("MainWindow", "Load"))
        self.Clear_3.setText(_translate("MainWindow", "Clear"))
        self.Device_Control_1.setTitle(_translate("MainWindow", "Device Control"))
